# Generated by Django 2.2.10 on 2021-09-11 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0014_auto_20200618_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='thumb_path',
            field=models.CharField(default=123, max_length=60),
            preserve_default=False,
        ),
    ]
