# Generated by Django 2.2.10 on 2021-09-12 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0016_stream'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stream',
            old_name='started_at',
            new_name='datetime',
        ),
    ]
